# Generated by Django 2.2.7 on 2020-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('smobile', models.BigIntegerField()),
                ('scourse', models.CharField(max_length=50)),
                ('sloc', models.CharField(max_length=50)),
            ],
        ),
    ]
