# Generated by Django 3.0 on 2020-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_feedbackdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
